/** Declaration file generated by dts-gen */


declare namespace server {
    function createSchema(db: object): object;
	function checkAuth(User: object): any;
	function createAuth(Model: object): any[];
}

