/** Declaration file generated by dts-gen */


declare namespace server {
    export function createSchema(db: object): object;
	export function checkAuth(User: object): any;
	export function createAuth(Model: object): any[];
}

